### ISSUE TITLE
Test error

### ISSUE THREAD

**Issue by martin-spa** [technipelago/sequence-rest-service#1]
In `se.technipelago.sequence.SequenceServiceIntegrationTests.testSequences()`

> The method update(Long, String, String, Long, Long) in the type SequenceNumberService is not applicable for the arguments (long, String, String, long).

Probably it has to be updated with the missing parameter.

**Comment by goeh** [comment]
Thank you for reporting this! Fixed by 1ca4717c7e85f14c889f3324428b89a4ea5134fb
